LOCAL_SRC_PATH = "/Users/eduard/PhpstormProjects/exam"

$script_once = <<-SCRIPT
if [ !  -f /root/.provisioned ]; then
    cp /vagrant/install.sh /root/.
    sh /root/install.sh
fi
SCRIPT

$script_always = <<-SCRIPT
systemctl start nginx
SCRIPT

PRIVATE_IP = "192.168.12.100"
VM_SRC_PATH = "/var/www/exam/"

Vagrant.configure("2") do |config|
  config.vm.provision "shell" do |s|
    s.inline = "echo Provisioning..."
    s.binary = true
  end
  config.vm.define "exam" do |exam|
    exam.vm.box = "bento/ubuntu-18.04"
    config.vm.network :private_network, ip: PRIVATE_IP
    config.vm.provision "shell", inline: $script_once, run: "once"
    config.vm.provision "shell", inline: $script_always, run: "always"
    config.vm.hostname =  "exam.dev"
    config.vm.synced_folder LOCAL_SRC_PATH, VM_SRC_PATH, group:"www-data", owner:"vagrant", mount_options: ["dmode=775,fmode=774"]
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--memory', 6048]
        vb.customize ['modifyvm', :id, '--cpus', 4]
    end
  end
end
